# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, QuickCheck, random, spoon, tasty, tastyHunit, transformers
}:

cabal.mkDerivation (self: {
  pname = "quickspec";
  version = "0.9.6";
  src = ./.;
  buildDepends = [ QuickCheck random spoon transformers ];
  testDepends = [
    QuickCheck random spoon tasty tastyHunit transformers
  ];
  meta = {
    homepage = "https://github.com/nick8325/quickspec";
    description = "Equational laws for free!";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
